version: 2
jobs:
  simple-job1:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/dmp
    steps:
      - checkout
      - run: 
          command: |
            echo "this is my first job"
           
            
  simple-job2:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: 
          command: |
            echo "this is my second job"
            
 
workflows:
  version: 2
  cms-workflow:
    jobs:
      - simple-job1
        
      - simple-job2:
          type: approval
          requires: 
            - simple-job1
            
        
