version: 2

dockerimage: &dockerimage
  docker:
      - image: circleci/openjdk:8-jdk
  working_directory: ~/dmp

jobs:
  simple-job1:
    <<: *dockerimage
    
    steps:
      - checkout
      - run: 
          command: |
            echo "this is my first job"
           
            
  simple-job2:
    <<: *dockerimage
    steps:
      - checkout
      - run: 
          command: |
            echo "this is my second job"
            
 
workflows:
  version: 2
  cms-workflow:
    jobs:
      - simple-job1
        
      - simple-job2:
          type: approval
          requires: 
            - simple-job1
            
        
