version: 2
jobs:
  simple-job1:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/dmp
    steps:
      - checkout
      - run: 
          command: |
            echo "this is my first build"
            mvn clean install -Dmaven.test.skip=true
            
            
  simple-job2:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: 
          command: |
            echo "this is my first build"
            mvn clean install -Dmaven.test.skip=true
            
 
workflows:
  version: 2
  cms-workflow:
    jobs:
      - simple-job1
      - simple-job2
    
            
        
